# **Linear algebra**  
### Vectors:
#### 1. Definition
Vectors can be interpreted differently depending on the context. Originally, in mathematics and physics, vectors were used to describe a direction and magnitude. Most common vectors are Euclidean vectors, which carries a point $A$ to a point $B$ in a straight line, noted $\vec{AB}$. The magnitude of $\vec{AB}$ is the distance between $A$ and $B$. The direction of $\vec{AB}$ is the angle between straight line $\vec{AB}$ and the unit vector $\vec{O}$ (arrow that defines the abscissa, acts like an origin of the vector space).

In computer science, a vector is a sequence of numbers defined as a one dimensional array. Unlike Euclidean vectors, vectors in computer science are not necessarily straight lines. For example, a vector can be a sequence of numbers that represent a point in a two dimensional space or more. Those numbers are called scalars. A scalar is just a floating point number, and can also be seen as a real number even in the Euclidean geometry.

We count two types of vectors: row vectors and column vectors. Row vectors are defined as arrays of one line and multiple columns, while column vectors are defined as arrays of multiple lines and one column.

$$v_{row} = \begin{bmatrix}x_0 & x_1 & x_2\end{bmatrix}, v_{column} = \begin{bmatrix}x_0 \\ x_1 \\ x_2\end{bmatrix} $$

**Note**: A vector space is simply a set of vectors.

#### 2. Arithmetic operations
Suppose $V_A$ and $V_B$ are vectors. We can add them together, subtract them, multiply them, and divide them as long as the dimensions are the same.
$$v_a + v_b = \begin{bmatrix}x_0 + y_0 & x_1 + y_1 & ... & x_n + y_n\end{bmatrix}$$
Where $n$ is the number of elements in the vectors.  
We can also multiply a vector by a scalar.
$$v_a \times c = \begin{bmatrix}x_0 \times c & x_1 \times c & ... & x_n \times c\end{bmatrix}$$

In [13]:
import numpy as np
a, b = np.array([1, 2, 3]), np.array([4, 5, 6])
print(a + b, a - b, a * b, a / b)

c = 3
print(a + c, a - c, a * c, a / c)

[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ]
[4 5 6] [-2 -1  0] [3 6 9] [0.33333333 0.66666667 1.        ]


#### 3. Inner product (dot product):
The inner product of two vectors $V_A$ and $V_B$ is the sum of the products of the corresponding elements:
$$\langle v_a, v_b \rangle = \sum_{i=0}^{n} x_i \times y_i$$
**Note**: $\langle v_a, v_b \rangle$ can also be written as $v_a \cdot v_b$.

In [20]:
print(a, b, 'inner product = {}'.format(np.dot(a, b)))

[1 2 3] [4 5 6] inner product = 32


#### 4. Norms:
The norm of a vector $v_a$ is a function that outputs a non-negative real number $norm: X \rightarrow \mathbb{R}$ where $X$ is the vector space. This real number can have different meanings depending on the context. For example, the Euclidean norm or 2-norm can be used to measure the distance from the origin.
$$|v_a|_2 = \sqrt{\sum_{i=0}^{n} x_i^2}$$
The absolute value of a vector is a 1-norm and is represents the magnitude of the vector.

**p-norm:** normalization comes in a more general formula noted as $\mathbf{l}_p$-norm. where $p > 0$.
- $p = 1$: the 1-norm is the absolute value of the vector, also called Taxicab norm or Manhattan norm.
$$|v_a|_1 = \sum_{i=0}^{n} |x_i|$$
- $p = 2$: the 2-norm is the Euclidean norm.
$$|v_a|_2 = \sqrt{\sum_{i=0}^{n} x_i^2}$$
- $p > 2$: the p-norm is the p-th root of the sum of the p-th powers of the elements of the vector.
$$|v_a|_p = \left({\sum_{i=0}^{n} |x_i|^p}\right)^{\frac{1}{p}}$$

#### 5. Linear combination: 
The linear combination of a set $V$ of vectors is the sum of all the vectors in $V$ multiplied by their corresponding scalar coefficients.
$$v = a_1v_1 + a_2v_2 + ... + a_nv_n$$ 
**e. g.** $(a_1, a_2, a_3) = a_1(1, 0, 0) + a_2(0, 1, 0) + a_3(0, 0, 1)$

#### 6. *Linear indenpendence:*
Two vectors $v_a$ and $v_b$ are said to be linearly dependent if there is a combination of non-zero scalars such a:
$$a_1v_1 + a_2v_2 + ... + a_nv_n = 0$$
If the only solution to this linear combination is zero $(a_1, a_2, ..., a_n) = (0, 0, ..., 0)$, then the vectors are linearly independent. In other words, if we can express the vectors as two different linear combinations, then the vectors are linearly dependent:  
(1) $a_1v_1 + a_2v_2 + ... + a_nv_n = 0$  
(2) $b_1v_1 + b_2v_2 + ... + b_nv_n = 0$  
if we put $(1) - (2) = 0$ and $c_i := a_i - b_i$ then we have:  
$\Longrightarrow c_1v_1 + c_2v_2 + ... + c_nv_n = 0$; if the only solution to this linear combination is $c = [0, 0, ..., 0]$ then the vectors are linearly independent, otherwise they are dependent.

#### 7. Orthogonal and orthonormal vectors
A vector $v_a$ is said to be orthogonal to a vector $v_b$ if the inner product of $v_a$ and $v_b$ is zero. From a geometric point of view, we say that 2 vectors are orthogonal if they are perpendicular to each other.
$$v_a, v_b \in V \Longrightarrow \langle v_a, v_b \rangle = 0$$

We say that a set of vectors ${v_1, v_2, ..., v_n}$ are mutually orthogonal if every pair of vectors is orthogonal.
$$\forall v_i, v_j \in V, \langle v_i, v_j \rangle = 0; i \neq j$$

A set of vectors $V$ is said to be orthonormal if it is mutually orthogonal and every vector is a unit vector. A unit vector (or normal vector) is a vector that has a magnitude (or norm) of 1, so for example:

$$\text{we put as vector set} \;\;\; V = \left\{\begin{bmatrix}1 \\ 0 \\ -1\end{bmatrix}, \begin{bmatrix}1 \\ \sqrt{2} \\ 1\end{bmatrix}, \begin{bmatrix}1 \\ -\sqrt{2} \\ 1\end{bmatrix}\right\}$$

Those vectors are orthogonal but not orthonormal, $\forall v_i, v_j \in V | i \neq j \Rightarrow \langle v_i, v_j \rangle = 0$.  
$$\text{we put} \;\;\; u_i = \frac{v_i}{|v_i|}; \forall v_i \in V$$
The set of vectors $u_i$ is orthogonal and orthonormal, its also called the orthonormal basis of $V$.

#### 8. Cosine similarity:
The cosine similarity between two vectors $v_a$ and $v_b$ is the cosine of the angle between the vectors. This formula can be derived from the inner product (dot product) of two vectors in an Euclidean space. The original inner product formula is:
$$\langle \vec{u}, \vec{v} \rangle = \|\vec{u}\| \times \|\vec{v}\| \times cos(\hat{\vec{u}, \vec{v}})$$
If we put $\theta$ as the angle between the vectors, then the cosine similarity formula is:
$$\cos \theta = \frac{\langle v_a, v_b \rangle}{|v_a| \times |v_b|}$$
The value of the cosine similarity is between -1 and 1. -1 if the two vectors are in different directions, 0 if they are orthogonal, and 1 if they are colinear and therefore, a positive scalar $k$ exists such as $\vec{u} = k\vec{v}$. Cosine similarity is used as a metric to measure the similarity between two vectors, the closer the value is to 1, the more similar the vectors are.

### **Matrices:**

### **Eigenvalues and eigenvectors:**