# **Linear algebra**
### <u>Vectors:</u>
#### 1. *Definition*
Vectors can be interpreted differently depending on the context. Originally, in mathematics and physics, vectors were used to describe a direction and magnitude. Most common vectors are Euclidean vectors, which carries a point $A$ to a point $B$ in a straight line, noted $\vec{AB}$. The magnitude of $\vec{AB}$ is the distance between $A$ and $B$. The direction of $\vec{AB}$ is the angle between straight line $\vec{AB}$ and the unit vector $\vec{O}$ (arrow that defines the abscissa, acts like an origin of the vector space).

In computer science, a vector is a sequence of numbers defined as a one dimensional array. Unlike Euclidean vectors, vectors in computer science are not necessarily straight lines. For example, a vector can be a sequence of numbers that represent a point in a two dimensional space or more. Those numbers are called scalars. A scalar is just a floating point number, and can also be seen as a real number even in the Euclidean geometry.

We count two types of vectors: row vectors and column vectors. Row vectors are defined as arrays of one line and multiple columns, while column vectors are defined as arrays of multiple lines and one column.

$$V_{row} = \begin{bmatrix}x_0 & x_1 & x_2\end{bmatrix}, V_{column} = \begin{bmatrix}x_0 \\ x_1 \\ x_2\end{bmatrix} $$

**Note**: A vector space is simply a set of vectors.

#### 2. *Arithmetic operations*
Suppose $V_A$ and $V_B$ are vectors. We can add them together, subtract them, multiply them, and divide them as long as the dimensions are the same.
$$V_A + V_B = \begin{bmatrix}x_0 + y_0 & x_1 + y_1 & ... & x_n + y_n\end{bmatrix}$$
Where $n$ is the number of elements in the vectors.  
We can also multiply a vector by a scalar.
$$V_A \times c = \begin{bmatrix}x_0 \times c & x_1 \times c & ... & x_n \times c\end{bmatrix}$$

In [13]:
import numpy as np
a, b = np.array([1, 2, 3]), np.array([4, 5, 6])
print(a + b, a - b, a * b, a / b)

c = 3
print(a + c, a - c, a * c, a / c)

[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ]
[4 5 6] [-2 -1  0] [3 6 9] [0.33333333 0.66666667 1.        ]


#### 3. *Inner product (dot product):*
The inner product of two vectors $V_A$ and $V_B$ is the sum of the products of the corresponding elements:
$$\langle V_A, V_B \rangle = \sum_{i=0}^{n} x_i \times y_i$$
$\langle V_A, V_B \rangle$ can also be written as $V_A \cdot V_B$.

In [20]:
print(a, b, 'inner product = {}'.format(np.dot(a, b)))

[1 2 3] [4 5 6] inner product = 32


#### 4. *Norms:*
The norm of a vector $V_A$ is a function that outputs a non-negative real number $norm: X \rightarrow \mathbb{R}$ where $X$ is the vector space. This real number can have different meanings depending on the context. For example, the Euclidean norm or 2-norm can be used to measure the distance from the origin.
$$|V_A|_2 = \sqrt{\sum_{i=0}^{n} x_i^2}$$
The absolute value of a vector is a 1-norm and is represents the magnitude of the vector.

**p-norm:** normalization comes in a more general formula noted as $\mathbf{l}_p$-norm. where $p > 0$.
- $p = 1$: the 1-norm is the absolute value of the vector, also called Taxicab norm or Manhattan norm.
$$|V_A|_1 = \sum_{i=0}^{n} |x_i|$$
- $p = 2$: the 2-norm is the Euclidean norm.
$$|V_A|_2 = \sqrt{\sum_{i=0}^{n} x_i^2}$$
- $p > 2$: the p-norm is the p-th root of the sum of the p-th powers of the elements of the vector.
$$|V_A|_p = \left({\sum_{i=0}^{n} |x_i|^p}\right)^{\frac{1}{p}}$$